### ISSUE TITLE
Bat Wing given nogreed tag instead of Ice Cube

### ISSUE THREAD

**Issue by Hythonia** [UnderscoreKilburn/repentance-issues#1123]
With 1.7.9 several trinkets were given the nogreed tag as nigh-useless in Greed Mode. While A Lighter was removed, Ice Cube was not. Given Ice Cube has ID 188 and Bat Wing has ID 118, I assume this to be a mistake, seeing as Bat Wing is far from useless in Greed Mode.

**Comment by ZMBanshee** [comment]
Yeah that was a mistake, misread the ID. Thanks for reporting that. 

I would be interested to see a few of these trinkets possibly gain functionality in this mode later, depending on what Kil wants to do. This is pretty much just meant to be a "for now" type solution since there's a been a lot of other more important things going on lately.
