### ISSUE TITLE
Tainted Bethany Black Bean Bug

### ISSUE THREAD

**Issue by ViviReal** [UnderscoreKilburn/repentance-issues#1147]
https://user-images.githubusercontent.com/117789118/200714288-fcdd170f-12b4-459b-93c5-eafbfc41ca43.mp4

While playing T Beth, I got Black Bean from the wisps and this ended up happening. I don't know if this is how new BB works, but I don't think it is.

**Comment by ViviReal** [comment]
It went on like this until I left the boss room.

**Comment by ZMBanshee** [comment]
It's likely a mod related issue. The Black Bean has a new cooldown parameter defined in items.xml that it needs to control the fart frequency. If a mod is replacing this file with an older version, it will break this, and several of the other reworked items.

If you can get this to happen with all of your mods off, post another comment here, otherwise I will close this eventually as this tracker is intended to be used for issues pertaining to the vanilla game.
