### ISSUE TITLE
another infinite glowing hourglass method

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#1173]
pretty sure this is impossible to fix? lol
but yeah

if you put glowing hourglass inside of moving box, this way you just need to do that everytime you wanna abuse it.

it puts you in the state before you used moving box hence you can do it infinitely

**Comment by ZMBanshee** [comment]
I don't think it's impossible to fix. Upon looking at this, I see that Moving Box actually does remember how many uses GHG is supposed to have, if it had already been used before packing it. This fact alone shows us that the amount of GHG uses inside Moving Box can be properly tracked already, meaning it may be possible to account for this case and decrement the uses while it's inside the box.

**Comment by ZMBanshee** [comment]
It seems like part of the problem is that the rewind function isn't entirely restoring the details about Moving Box contents, at least when it comes to the amount of uses of a stored GHG.

However, it does restore other crucial details about Moving Box contents, such as the charge of stored active items. Since it's just presumably just a variable in both cases, I don't see why it couldn't remember the amount of GHG uses inside the Box.

Here's a video where I demonstrate this oversight:
https://www.youtube.com/watch?v=q-2MSgATaZQ

If it were updated to keep track of this, the rewind would then need to decrement the use of a stored one if it didn't find a real GHG in your inventory. Voila, bug fixed... well, at least in theory. Obviously Kil is going to have to take a look at this, but it seems fixable, even if it's a pretty technically involved bug.

**Comment by Lonrite** [comment]
damn nice investigation right there, I do hope _Kil sees it since you put good effort into looking through this
