### ISSUE TITLE
Golden kid's drawing with a guppy part doesn't give you flight right away

### ISSUE THREAD

**Issue by ez-duke** [UnderscoreKilburn/repentance-issues#1385]
But you get flight after save&quitting or on a new floor

**Comment by Rchardon** [comment]
or picking up an item

**Comment by ZMBanshee** [comment]
The bug doesn't seem to be specific to the golden version.

**Comment by dluengo** [comment]
Apparently if Guppy's transformation depends on Kid's drawing, dropping the trinket and picking it back triggers the transformation again but you don't get fly, you get fly generation though.

I'm not sure if that's just it or if there are more implications. I think I haven't experience this behavior before (I play a lot and I had the transformation because of the trinket many times before). In the run I got triggered this issue, among other things, I had Pluto, my guts suggest it may have something to be.

My seed was 66A2 VGHA.
