### ISSUE TITLE
Windows Defender now thinks the game is a virus

### ISSUE THREAD

**Issue by Heroshrine** [UnderscoreKilburn/repentance-issues#1428]
After the most recent update, windows defender now thinks the game is a virus and steam cannot launch the game.

**Comment by ZMBanshee** [comment]
This is a problem on Microsoft's end, an update to Windows Defender caused this false positive. It is not an issue with the game itself. The last update to the game was a week ago, and this issue only popped up yesterday after a Windows update.

There's not much the developers can do, so I'm going to close this issue. You should add an exception for the necessary files in Windows Defender so that you can still play the game in the meantime.
