### ISSUE TITLE
More trinkets to remove from greed mode

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#164]
Purple heart (since it just makes enemies harder without dropping anything)
Temporary tattoo
Karma
Fragmented Card
Crystal Key
A Lighter (doesn't work on waves)
Ice Cube (doesn't work on waves)
Nuh Uh!
Old Capacitor (since there's no battery spawning)

Idea from https://www.youtube.com/watch?v=CKYy0W_h4LY

**Comment by ZMBanshee** [comment]
Some of these trinkets just got removed, there are a handful that are not removed but also not functional yet (Ice Cube, A Lighter, Fragmented Card). So this is only partially fixed, but ideally the ones that are still in should be updated to work instead of being removed. I may open a new issue for these specific ones later, but if you have any more to add here then go ahead and reopen it yourself.
