### ISSUE TITLE
Henry doesn't have a game over sprite

### ISSUE THREAD

**Issue by DO97** [UnderscoreKilburn/repentance-issues#1832]
When you accidentally die versus Henry (it is possible), the rarest enemy, your game over screen doesn't show its sprite as for the other enemies in the game.

**Comment by Rchardon** [comment]
It isn't in the bestiary either so no need to bother for that

**Comment by DO97** [comment]
> It isn't in the bestiary either so no need to bother for that

I know well, but it's still an enemy and it might kill you. It makes sense to show its sprite when this happens.

**Comment by Rchardon** [comment]
It makes no sense to me to do something for an event that had less chances to happen than the missile appearing after killing baby plum (1/1000000 chance). Henry is in one and only room that has one door in only one floor. That makes it around 1/500000 chance to appear in a Dross floor per run. What are also the probabilities that you run into it and dying because you hit it three times (maximum you can get hit before it disappears) ?
So for a thing that is less likely to a person than winning the lottery, it doesn't make sense for me. (And by default it has a game over sprite, it's not henry but it's not nothing)
