### ISSUE TITLE
Poke Go ( or card reading ) softlock

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#2078]
noticed someone having this, pretty sure it has to do something with enemy being in the room so the wall doesn't open?

also could be from card reading but idk 4sho

https://youtu.be/sIUFCiDDFRg?si=8pJdR8UGuaj44Fzl

**Comment by ZMBanshee** [comment]
I checked the seed and it's caused by the same bug as https://github.com/UnderscoreKilburn/repentance-issues/issues/1626 but this did give me a better understanding of why it occurs (the door will start open, but if enemies are in the room layout or spawned by button it won't open again if the exit is to a challenge room you don't have the health requirement for)

**Comment by Lonerite** [comment]
ah lol, that's a shame
that dude's or dudette's run looked sick af

**Comment by Lonrite** [comment]
ah lol, that's a shame
that dude's / dudette's run looked sick af
