### ISSUE TITLE
Ultra Greed coin obsession

### ISSUE THREAD

**Issue by Lonrite** [UnderscoreKilburn/repentance-issues#2083]
his coin attack in phase 1 (the one where the slot spin doesn't pay out) is the single worst attack in the entire game, easily

I tested it numerous times and you can't even prevent it falling on top of you instantly by standing still (it's heavily inconsistent) so you're just left at the mercy of RNG

it should at least have a bigger shadow / less coins / longer telegraph / not be able to fall down on you if you stand still. (or all of these combined LOL)

It's genuinely the reason 2nd phase is more well-designed, his 1st phase could've been near-flawless (fairness-wise I mean, he doesn't bring something ultra unique to the table for the most part, even if it's just me) if not for that - which is a shame

**Comment by Lonrite** [comment]
https://clips.twitch.tv/VibrantBreakableGrasshopperTheThing-UukHBs2R7EtgMUVo

like this is not much different from Delirium's telefrags lol, there were some other instances which looked even worse that I didn't clip 

it's like coming to an exam with full knowledge about the subject, but your pen gets taken away and you get told you need to finish it under time constraints. it's difficult, sure - but in a bullshit, artificial way

**Comment by ZMBanshee** [comment]
I've tested this with larger/more visible shadows and that seems to be much better. So hopefully that will be changed at some point as it's pretty easy to fix.

**Comment by Lonrite** [comment]
> I've tested this with larger/more visible shadows and that seems to be much better. So hopefully that will be changed at some point as it's pretty easy to fix.

unlikely but I hope so as well

**Comment by Lonrite** [comment]
also offtopic but some bosses have insanely tiny unpredictable shadows on none at all, like Triachnid and it's very annoying

blastocyst has an annoying boss room as well where the big one shows up like on the upper left corner without a tell 

but w/e

**Comment by ZMBanshee** [comment]
Whoever made that Blastocyst room put a smaller one in the middle, so that the bigger one would drop in as a surprise. I knew when I saw it that it might not be completely fair to someone who has never seen it before, as they might walk up there to the corner. I put a rock there near the top door to try and hinder movement in that direction but obviously that's not going to help for anyone who's flying, lol. There's not really a way to make it 100% fair while keeping the surprise part of it. I guess it's just something to learn and remember.
