### ISSUE TITLE
Multiple items should be removed from their respective pools in Greed Mode on account of doing nothing in Greed Mode

### ISSUE THREAD

**Issue by AyyItsClarkster** [UnderscoreKilburn/repentance-issues#254]
Guppy's Tail (Greed Curse Room, Greed Devil Room (arguable, since it's still a Guppy item))
Poke Go, Treasure Map, Voodoo Head (Greed Shop)
Death's List (Greed Devil Room)
Glyph of Balance (Greed Angel Room (arguable since it does give 2 soul hearts, but no other effect))

All of these items practically (in Voodoo Head's case, literally) have no effect in Greed Mode, and following the logic of certain items that have the nogreed item tag or were removed from Greed Mode pools in the past, so too should these be.

**Comment by ZMBanshee** [comment]
I do want to keep Tail for the sake of the transformation (it's surprisingly very relevant for that alone) even if the golden chest effect won't do too much. Poke Go should ideally be updated to spawn friends during the waves instead of being removed.

Treasure Map and Voodoo Head are already not present in Greed mode.

I can agree that Death's List doesn't belong unless Kil really wants to make it work per wave... really though with how chaotic the mode is I doubt the effect would get much mileage even if it worked.

**Comment by AyyItsClarkster** [comment]
I completely misread the infobox on the wiki regarding Treasure Map and Voodoo Head, my mistake. I agree, ideally Poke Go and Death's List should be updated to work in Greed Mode.

**Comment by AyyItsClarkster** [comment]
I figured item tags and item pools should get different posts; not really used to github etiquette lol, bare with me. but in this vein, these items should all get the nogreed item tag for similar reasons as items that currently have it

Contract from Below, Death's List, Duality, Glyph of Balance, Goat Head, Mitre, Poke Go, Treasure Map, Voodoo Head (unless these are changed somehow, as above)

**Comment by ZMBanshee** [comment]
Contract From Below, Duality, Goat Head, Mitre, Treasure Map, Voodoo Head are all not there already. 

Death's List is there but will get removed now (a comeback later is possible). Glyph of Balance can slide on account of not being worthless, but maybe later it could be updated to let champions drop rewards there. Ideally stuff should just work if they could be applicable.
