### ISSUE TITLE
C Section + Soy milk + Kidney stone doesn't shoot fetuses until Kidney stone effect is off

### ISSUE THREAD

**Issue by Rchardon** [UnderscoreKilburn/repentance-issues#31]

**Comment by ZMBanshee** [comment]
Upon further inspection this issue starts happening once you reach 30 tears per second with C Section and isn't specific to Kidney Stone. I'm keeping a list of items that stop functioning at 30 tears per second in a separate issue, so I've now added it there. I'll close this now since it's redundant, but thanks for the report.
