### ISSUE TITLE
Fighting the beast as Tainted Lazarus and changing forms will cause the form without Dogma/Flight to plummet into the lava.

### ISSUE THREAD

**Issue by freezingdart** [UnderscoreKilburn/repentance-issues#34]
see title

**Comment by ZMBanshee** [comment]
Is this happening to you without any mods whatsoever? I could not reproduce this on a completely vanilla game. There's a new system in place to allow Lazarus forms to share certain items, and Dogma is one of them. It's using a new tag in the items_metadata.xml file to determine which items need to be shared, outdated mods that replace this file won't have it. Something seemingly completely unrelated could break this as a result, but it doesn't belong here if a mod is the cause.

**Comment by ZMBanshee** [comment]
I'm gonna chalk this one up as mod related, feel free to reopen if that is not the case.

**Comment by Gemboat** [comment]
I can encounter this issue without any mods active... albeit in highly specific circumstances.
If you enter the Beast fight without Birthright, and then gain Birthright before flipping, the issue happens. While not _impossible_ in vanilla gameplay it's clearly not what anyone's run into, but does make it more likely those might not have been mod issues.

But also surely the real bug here is that the inactive Birthright Lazarus can be damaged by the lava in the Beast fight at all. _That_ at least is trivial to reproduce, since it doesn't need any weird setup.
Unlike the other methods in the game to damage a Birthright Tainted Lazarus (e.g. mausoleum door, shard of glass bleedout), this one feels very much unintended.
