### ISSUE TITLE
Forsaken + Uranus

### ISSUE THREAD

**Issue by ghost** [UnderscoreKilburn/repentance-issues#35]
Having a frozen skeleton makes the Haunt not reappear to fight

**Comment by ZMBanshee** [comment]
I believe you're talking about The Forsaken (especially since you mentioned a frozen skeleton). Haunt has no problem with Uranus.

Fortunately if you push the frozen bony and cause him to shatter, Forsaken will reappear. I guess it's not ideal though to have to do that, so I'll leave this open in case Vinh wants to take care of that.

**Comment by ghost** [comment]
> I believe you're talking about The Forsaken (especially since you mentioned a frozen skeleton). Haunt has no problem with Uranus.


oh I messed up the name. Thanks
