### ISSUE TITLE
Rune bag creates only 1 type of rune / soul stone (in my case soul of the lost) as dead tainted lazarus.

### ISSUE THREAD

**Issue by LegSow** [UnderscoreKilburn/repentance-issues#41]

**Comment by amb2127** [comment]
this happened to me on other characters, and on other items as well (dark bum spamming tears down)

**Comment by tmartrano** [comment]
Can confirm that this also happens with the sack of pennies on Tainted Lazarus only. It seems like every time the sack disappears and comes back due to the flip, it reuses the seed that is calculated to be the "first" drop for the bag. ie: If the sack drops a dime all subsequent drops will be a dime due to the bag being reinitialized with the same seed upon flipping. The issue is not relevant to either form of tainted Lazarus, but is related to the flipping between characters.
