### ISSUE TITLE
Champion Bosses Use Incorrect Sprites/Sprites Have Red Tint Applied

### ISSUE THREAD

**Issue by AttackTeam1** [UnderscoreKilburn/repentance-issues#553]
The Sprite appears to be that of the standard version, but with a red tint applied
![Sprite](https://user-images.githubusercontent.com/94146431/159408048-113d13b9-710c-49b2-b5ca-534c62276d07.PNG)

**Comment by AyyItsClarkster** [comment]
https://i.imgur.com/jSGpC14.png
this is the grey champion Death; he doesn't look the part does he? This also happens to black champion War. It seems they don't have sprites for their 2nd phases (they certainly don't exist in the resource files) so the game gets confused.
https://i.imgur.com/Y0J15rs.png
https://i.imgur.com/cb3grco.png
strangely, they both turn red permanently if they take damage in the 2nd phase. I guess the game's a bit confused on what to do since shaders aren't used for champion bosses anymore?

**Comment by AyyItsClarkster** [comment]
Champion Rag Man also doesn't seem to have sprites for the body, nor the detached head entity.  one of these is the champion form, the other isn't, place your bets for which one's which!
![hzBog9n](https://user-images.githubusercontent.com/38641261/159418752-76b6d8ca-ec89-484c-b5b6-1cb21fb22462.png)
