### ISSUE TITLE
curse of the tower crashes game in today's daily challenge

### ISSUE THREAD

**Issue by eyhung** [UnderscoreKilburn/repentance-issues#638]
I had curse of the tower and bird cage in today's daily challenge (rerolled into it using the dice room in floor 2).  When I got hit, troll bombs were summoned and then the game crashed.  I suspect bird cage was the culprit.

**Comment by ZMBanshee** [comment]
Crashes in dailies (especially in seemingly random cases like these) I'm going to chalk up as being caused by toggling off mods without doing a clean restart of the game. This game really does not unload mods very well from what I've seen. Some graphical changes even still persist in the middle of dailies in some cases.

**Comment by eyhung** [comment]
OK.  Yes, I did turn off mods without doing a clean restart, so sounds like this is probably the case.
