### ISSUE TITLE
Cube of Meat is still in the Greed Curse Room pool, despite patch notes saying it was removed from all pools except silver treasure and shop.

### ISSUE THREAD

**Issue by mouthwideopen** [UnderscoreKilburn/repentance-issues#666]
https://media.discordapp.net/attachments/485133685881045014/967115343204085860/unknown.png?width=1358&height=676 Mystery Gift has blessed me here with Cube.

I also checked the itempools.xml file itself. Still in there. https://media.discordapp.net/attachments/485133685881045014/967115784813957150/unknown.png

**Comment by ZMBanshee** [comment]
Apologies for the confusion (and late reply), but I believe the mistake here was with the patch notes, rather than the fact that it's still there. It only got removed from the devil, angel, and golden treasure room pools.

If you would like it to be removed, we can tag this as a suggestion and reconsider it. If you were simply reporting this as a bug, we can close this instead, but the attention to detail is appreciated nonetheless.
