### ISSUE TITLE
Butt bombs costume error?

### ISSUE THREAD

**Issue by ghost** [UnderscoreKilburn/repentance-issues#92]
![image](https://user-images.githubusercontent.com/62573470/141695085-2924282f-c3be-435c-81d7-01e00af2d375.png)
This is when I **shoot** up

![image](https://user-images.githubusercontent.com/62573470/141695105-08d6d1af-a769-4730-9db9-ff8f4c490f15.png)
this is when I **move** up

The costume only applies when I move.

**Comment by ZMBanshee** [comment]
As far as I know, the reason is because the head and the body are handled separately, and simply shooting doesn't turn Isaac's body around. It's not noticeable with most costumes, just a few. Whether this is a bug is kind of debatable, though, it was probably made to work this way because it doesn't look weird 99% of the time.
