### ISSUE TITLE
The switch patch is still missing a couple of things.

### ISSUE THREAD

**Issue by GentleSin37** [UnderscoreKilburn/repentance-issues#971]
Green champion Bloat's lasers are still red and orange little horn's bombs don't have their unique sprites in the latest switch patch. Also camo undies do not work in boss rooms.

**Comment by ZMBanshee** [comment]
Because it's not on the latest version. This is the latest version:
https://bindingofisaacrebirth.fandom.com/wiki/V1.7.8a

There isn't really any reason to report this here, because on the dev side of things this was fixed a long time ago. Nicalis just didn't port it. When the next patch comes out and they eventually port it, these fixes will be included.
